{
 "title": "Infinispan",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Number of Entries in TopicUsers",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "datagrid_cluster_cache_stats{attribute=\"number_of_entries\",container=\"local\",name=\"topicUsers\",}",
     "legendFormat": "Number of entries"
    }
   ]
  },
  {
   "title": "Current Number of Entries in TopicUsers",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "datagrid_cluster_cache_stats{attribute=\"current_number_of_entries_in_memory\",container=\"local\",name=\"topicUsers\",}",
     "legendFormat": "Current Number of entries"
    }
   ]
  },
  {
   "title": "Expired entries in TopicUsers",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "datagrid_cluster_cache_stats{attribute=\"stores\",container=\"local\",name=\"topicUsers\",}",
     "legendFormat": "Expired entries"
    },
    {
     "expr": "datagrid_cluster_cache_stats{attribute=\"number_of_entries\",container=\"local\",name=\"topicUsers\",}",
     "legendFormat": "Expired entries"
    }
   ]
  },
  {
   "title": "Avg RW in nanos",
   "type": "graph",
   "gridPos": { "h": 14, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "datagrid_cluster_cache_stats{attribute=\"average_read_time_nanos\",container=\"local\",name=\"topicUsers\",}",
     "legendFormat": "Avg R topicUsers"
    },
    {
     "expr": "datagrid_cluster_cache_stats{attribute=\"average_write_time_nanos\",container=\"local\",name=\"topicUsers\",}",
     "legendFormat": "Avg W topicUsers"
    },
    {
     "expr": "datagrid_cluster_cache_stats{attribute=\"average_read_time_nanos\",container=\"local\",name=\"vdbUsers\",}",
     "legendFormat": "Avg R vdbUsers"
    },
    {
     "expr": "datagrid_cluster_cache_stats{attribute=\"average_write_time_nanos\",container=\"local\",name=\"vdbUsers\",}",
     "legendFormat": "Avg W vdbUsers"
    }
   ]
  },
  {
   "title": "Number of Entries in vdbUsers",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "datagrid_cluster_cache_stats{attribute=\"number_of_entries\",container=\"local\",name=\"vdbUsers\",}",
     "legendFormat": "Number of entries"
    }
   ]
  },
  {
   "title": "Current Number of Entries in vdbUsers",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "datagrid_cluster_cache_stats{attribute=\"current_number_of_entries_in_memory\",container=\"local\",name=\"vdbUsers\",}",
     "legendFormat": "Current Number of entries"
    }
   ]
  },
  {
   "title": "Remove Hits in vdbUsers",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "datagrid_cluster_cache_stats{attribute=\"remove_hits\",container=\"local\",name=\"vdbUsers\",}",
     "legendFormat": "Remove Hits"
    }
   ]
  },
  {
   "title": "JVM Heap memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes", "label": "Memory" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"Code Cache\",}  ",
     "legendFormat": "Code Cache"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"Metaspace\",}",
     "legendFormat": "Metaspace"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"Compressed Class Space\",}",
     "legendFormat": "Compressed Class Space"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"PS Eden Space\",}",
     "legendFormat": "PS Eden Space"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"PS Survivor Space\",}",
     "legendFormat": "PS Survivor Space"
    },
    {
     "expr": "jvm_memory_pool_bytes_used{pool=\"PS Old Gen\",}",
     "legendFormat": "PS Old Gen"
    }
   ]
  }
 ]
}